AllCops:
  NewCops: enable
  Exclude:
    - bin/**
    - db/schema.rb
    - db/migrate/**

Layout/EndOfLine:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Metrics/MethodLength:
  Max: 20
