// Returns CSRF token generated by ruby to verify integrity.
// Make sure to set X-CSRF-Token header to this value when making POST/PUT requests.
export default function getCSRFToken(): string {
  return document.querySelector('meta[name="csrf-token"]')?.getAttribute('content');
}
